---
  - name: nginx
    apt: 
      name: nginx
  - name: start nginx
    service: 
      name: nginx
      state: started

  # - name: change default web page
  #   template:
  #     src: index.html
  #     dest: /var/www/
  
  - name: change config
    template:
      src: default.j2
      dest: /etc/nginx/sites-enabled/default
    notify: Restart Nginx

  - name: Execute handlers 
    meta: flush_handlers

  - name: waiting
    wait_for:
      timeout: 10

  - name: Check nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: change html
    template:
      src: index.html.j2
      dest: /var/www/html/index.nginx-debian.html
    when: inventory_hostname == groups['internal'][0]
    
  



  
  

  
 