---
  - name: nginx
    apt: 
      name: nginx
  - name: start nginx
    service: 
      name: nginx
      state: started

  # - name: change default web page
  #   template:
  #     src: index.html
  #     dest: /var/www/
  
  - name: change config
    template:
      src: default.j2
      dest: /etc/nginx/sites-enabled/default
    notify: Restart Nginx
    
  



  
  

  
 