--- 
- name: install grafana dependencies
  apt: 
   name: 
    - adduser
    - libfontconfig1
- name:  download grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.3.4_amd64.deb
    dest: /tmp/grafana_7.3.4_amd64.deb
- name: install grafana
  apt: 
    deb: /tmp/grafana_7.3.4_amd64.deb
- name: config grafana to show reverse proxy
  template:
    dest: /etc/grafana/grafana.ini
    src: grafana.ini.j2
  notify:
    - Restart Grafana
 


      

