---
- name: Create Grafana directories
  file:
    name: "{{ item }}"
    state: directory
    owner: "472"
    group: "472"
    recurse: true
  loop:
    - /opt/docker/grafana
    - /opt/docker/grafana-etc

- name: Setup Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    env:
      GF_SERVER_ROOT_URL: http://localhost:3000/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    ports:
      - "{{ docker_grafana_port }}:3000"
    volumes:
      - /opt/docker/grafana:/var/lib/grafana/
      - /opt/docker/grafana-etc:/etc/grafana/
