{
 "title": "service status",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "nginx status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "cpu load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=\"vm1:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"vm1:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"vm1:9100\"}) by (cpu))",
     "legendFormat": "vm1"
    },
    {
     "expr": "(((count(count(node_cpu{instance=\"vm2:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"vm2:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"vm2:9100\"}) by (cpu))",
     "legendFormat": "vm2"
    },
    {
     "expr": "(((count(count(node_cpu{instance=\"vm3:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"vm3:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"vm3:9100\"}) by (cpu))",
     "legendFormat": "vm3"
    }
   ]
  },
  {
   "title": "haproxy",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "keepalived",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "keepalived_up" }
   ]
  },
  {
   "title": "req per minute ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "keepalived",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "bind status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "DNs req per minute ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"vm1:9119\"}[1m])",
     "legendFormat": "vm1 {{  type  }}"
    },
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"vm2:9119\"}[1m])",
     "legendFormat": "vm2 {{ type }}"
    },
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"vm3:9119\"}[1m])",
     "legendFormat": " vm3{{ type }}"
    }
   ]
  }
 ]
}