---
- name: set up bind bind_exporter
  hosts: dns_server
  gather_facts: no
  become: yes
  roles:
    - bind_exporter
- name: set up mysqls bind_exporter
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql_exporter
  tags:
    - mysql
