---
- name: influxdb
  hosts: influxdb
  become: yes
  gather_facts: no
  roles:
   - influxdb
- name: pinger
  hosts: pinger
  gather_facts: false
  become: yes
  roles:
    - pinger
- name:  Rsyslog
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - rsyslog

