---
- name: Preparations for Ansible run
  hosts: all
  become: yes
  tasks:
  - name: Update cache
    apt:
      update_cache: yes
  - name: Remove unnecessary packages
    apt:
      autoremove: yes

# - name: Reconfigure DNS
#   hosts: dns_server
#   gather_facts: false
#   become: yes
#   roles:
#     - bind
- name: Configure backups
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - backup

