---
- name: set up bind bind_exporter
  hosts: dns_server
  gather_facts: no
  become: yes
  roles:
    - bind_exporter
- name: set up mysqls bind_exporter
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql_exporter
  tags:
    - mysql
- name: nginx exporter
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - nginx_exporter
  tags: 
    - nginx
- name: set up grafana
  hosts: grafana
  become: yes
  gather_facts: no
  roles:
    - grafana
  tags:
    - grafana