---
- name: Update Nginx configuration
  hosts: web_servers
  # gather_facts: false
  become: yes
  roles:
    - nginx

- name: Update DNS configuration
  hosts: dns_servers
  gather_facts: false
  become: yes
  roles:
    - bind

- name: Update backup facility configuration
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - backup

- name: Install docker
  hosts: docker
  gather_facts: false
  become: yes
  roles:
    - docker

- name: Reconfigure Prometheus
  hosts: prometheus
  gather_facts: false
  become: yes
  roles:
    - prometheus

- name: Setup Agama Docker container
  hosts: app_servers
  gather_facts: false
  become: yes
  roles:
    - agama_docker

- name: Install HAProxy and containerised haproxy exporter
  hosts: haproxy
  gather_facts: false
  become: yes
  roles:
    - haproxy

- name: Install keepalived and keepalived exporter
  hosts: haproxy
  gather_facts: false
  become: yes
  roles:
    - keepalived
