---
- name: init playbook 
  import_playbook: init.yaml
#first lab for test connectivity

- name: Ansible connection test
  hosts: all
  roles:
    - test_connection

# lab 2 web servers
- name: setup
  hosts: web_servers
  remote_user: ubuntu 
  become: yes
  roles:
    - users
    - nginx

- name: agama
  hosts: prometheus # აქ აგამა ორივეზე mysqld exporters არ აყენებს, აგამა მარტო პირველზე!
  remote_user: ubuntu
  become: yes
  roles:
   - agama
   - uwsgi
   #- nginx
# lab 4
- name: database app_servers
  hosts: db_servers
  become: yes
  roles:
    - mysql
- name: agama
  hosts: prometheus
  remote_user: ubuntu
  become: yes
  roles:
   - agama
   - uwsgi
   - nginx
# lab 5
- name: Gather facts
  hosts: all
  tasks:
    - setup:
- name: install bind9
  hosts: dns_server
  become: yes
  roles:
    - bind
- name: update vms dns settings
  hosts: dns_config
  become: yes
  roles:
   - dns
# lab 6 prometheus
- name: prometheus-node-exporters
  hosts: all
  become: yes
  roles:
    - node_exporter
- name: install prometheus on vm1
  hosts: prometheus
  become: yes
  roles:
    - prometheus
# lab 7 grafana
- name: set up bind bind_exporter
  hosts: dns_server
  gather_facts: no
  become: yes
  roles:
    - bind_exporter
- name: set up mysqls bind_exporter
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql_exporter
  tags:
    - mysql
- name: nginx exporter
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - nginx_exporter
  tags: 
    - nginx
- name: set up grafana
  hosts: grafana
  become: yes
  gather_facts: no
  roles:
    - grafana
  tags:
    - grafana
# lab8 logging
- name: influxdb
  hosts: influxdb
  become: yes
  gather_facts: no
  roles:
   - influxdb
- name: pinger
  hosts: pinger
  gather_facts: false
  become: yes
  roles:
    - pinger
- name:  Rsyslog
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - rsyslog

