---
# - name: Ensure backup folder exists.
#   file:
#     path: /home/backup
#     state: directory
#     owner: backup
#     group: backup
#     mode: 0775
- name: Add the user "backup" and genereate its keys
  user:
    name: backup
    create_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: /home/backup/.ssh/id_rsa

# - name: Add the user "backup" and genereate its keys
#   user:
#     name: backup
#     create_home: yes
#     generate_ssh_key: yes
#     ssh_key_bits: 4096
#     ssh_key_file: .ssh/id_rsa
# sudo chown -R username:group directory

