---
- name: install mysql exportert package
  apt: 
    name: prometheus-mysqld-exporter
    update_cache: yes

- name: config
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify: Restart mysql_exporter

- name: create an user for exporter 
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_pass }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT" #databasename.table
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: True
  notify: Restart mysql_exporter

- name: Enable mysqld exporter
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes

