---
- name: install mysql
  apt:
    name: mysql-server
    state: latest
- name: change mysql config
  template:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/
  notify:
    restart mysql
- name: Install PyMySQL for MySQL
  apt: 
    name: python3-pymysql
    state: latest
- name: MySQL database
  mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name : mysql user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
    # lab11
- name: Create MySQL replication user
  mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_pass }}"
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  notify:
    - Stop MySQL slave thread
    - Change MySQL master thread to use replication
    - Reset MySQL slave thread
    - Reset MySQL slave thread
    - Start MySQL slave thread


- name: Execute handlers 
  meta: flush_handlers

- name: waiting 
  wait_for:
    timeout: 10

- name: Check mysql
  service:
    name: mysql
    state: started
    enabled: yes


      