---
- name: config bin exporter
  apt:
    name: prometheus-bind-exporter
    state: latest
- name: prometheus error throw skip 
  wait_for:
      timeout: 20
- name: Enable Bind9 exporter
  service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes

