---
- name: Install Docker
  apt:
    name:
      - python3-docker
      - docker.io
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Execute handlers 
  meta: flush_handlers

- name: waiting 
  wait_for:
    timeout: 10

- name: Check if started
  service:
    name: docker
    state: started
    enabled: yes