---
  - name: nginx
    apt: 
      name: nginx
      update_cache: true
  - name: start nginx
    service: 
      name: nginx
      state: started 
      

  - name: change config
    copy:
      src: default.conf
      dest: /etc/nginx/sites-available/default
    notify: Restart Nginx
    
  



  
  

  
 