---
- name: Create the directory /opt/agama
  file:
    name: /opt/agama
    owner: root
    group: root
    state: directory
    recurse: true

- name: Download Dockerfile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile
    owner: root
    group: root
    mode: '777'

# - name: Transfer Agama Docker file
#   template:
#     src: Dockerfile.j2
#     dest: /opt/agama/Dockerfile
#     owner: root
#     group: root
#     mode: '777'

- name: Build Agama Docker image
  docker_image:
    name: agama
    build:
      path: /opt/agama
    source: build

- name: Setup Agama container
  docker_container:
    name: agama
    image: agama
    env:
     AGAMA_DATABASE_URI: mysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    ports:
      - "{{ docker_agama_port }}:8000"
